version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: yoja_db
    environment:
      POSTGRES_DB: yoja_db
      POSTGRES_USER: yoja_user
      POSTGRES_PASSWORD: yoja_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - yoja_network

networks:
  yoja_network:
    driver: bridge